"""empty message

Revision ID: 24c891ad64c6
Revises: c3d9c13e3f39
Create Date: 2021-03-01 15:53:13.555651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c891ad64c6'
down_revision = 'c3d9c13e3f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_recipe_cuisine_constraint', 'recipe_cuisines', ['recipe_id', 'cuisine_id'])
    op.create_unique_constraint('_recipe_dish_type_constraint', 'recipe_dish_types', ['recipe_id', 'dish_type_id'])
    op.create_unique_constraint('_recipe_ingredient_constraint', 'recipe_ingredients', ['recipe_id', 'ingredient_id'])
    op.create_unique_constraint('_recipe_tag_constraint', 'recipe_tags', ['recipe_id', 'tag_id'])
    op.create_unique_constraint('_user_role_constraint', 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_role_constraint', 'user_roles', type_='unique')
    op.drop_constraint('_recipe_tag_constraint', 'recipe_tags', type_='unique')
    op.drop_constraint('_recipe_ingredient_constraint', 'recipe_ingredients', type_='unique')
    op.drop_constraint('_recipe_dish_type_constraint', 'recipe_dish_types', type_='unique')
    op.drop_constraint('_recipe_cuisine_constraint', 'recipe_cuisines', type_='unique')
    # ### end Alembic commands ###
