"""diet type

Revision ID: b44444cef119
Revises: 1c1888098494
Create Date: 2021-03-03 07:36:59.595475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b44444cef119"
down_revision = "1c1888098494"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diet_types",
        sa.Column(
            "time_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "recipe_diet_types",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("diet_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["diet_type_id"],
            ["diet_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("recipe_id", "diet_type_id"),
        sa.UniqueConstraint(
            "recipe_id", "diet_type_id", name="_recipe_diet_type_constraint"
        ),
    )
    # op.create_unique_constraint('_recipe_cuisine_constraint', 'recipe_cuisines', ['recipe_id', 'cuisine_id'])
    # op.create_unique_constraint('_recipe_dish_type_constraint', 'recipe_dish_types', ['recipe_id', 'dish_type_id'])
    # op.create_unique_constraint('_recipe_tag_constraint', 'recipe_tags', ['recipe_id', 'tag_id'])
    # op.create_unique_constraint('_user_role_constraint', 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('_user_role_constraint', 'user_roles', type_='unique')
    # op.drop_constraint('_recipe_tag_constraint', 'recipe_tags', type_='unique')
    # op.drop_constraint('_recipe_dish_type_constraint', 'recipe_dish_types', type_='unique')
    # op.drop_constraint('_recipe_cuisine_constraint', 'recipe_cuisines', type_='unique')
    op.drop_table("recipe_diet_types")
    op.drop_table("diet_types")
    # ### end Alembic commands ###
