"""house meals

Revision ID: c3d9c13e3f39
Revises: 3452a6d71d6d
Create Date: 2021-03-01 13:25:45.356681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3d9c13e3f39"
down_revision = "3452a6d71d6d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meals", sa.Column("household_id", sa.Integer(), nullable=False))
    op.drop_constraint("meals_user_id_fkey", "meals", type_="foreignkey")
    op.create_foreign_key(None, "meals", "households", ["household_id"], ["id"])
    op.drop_column("meals", "user_id")
    # op.create_unique_constraint('_recipe_cuisine_constraint', 'recipe_cuisines', ['recipe_id', 'cuisine_id'])
    # op.create_unique_constraint('_recipe_dish_type_constraint', 'recipe_dish_types', ['recipe_id', 'dish_type_id'])
    # op.create_unique_constraint('_recipe_ingredient_constraint', 'recipe_ingredients', ['recipe_id', 'ingredient_id'])
    # op.create_unique_constraint('_recipe_tag_constraint', 'recipe_tags', ['recipe_id', 'tag_id'])
    # op.create_unique_constraint('_user_role_constraint', 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('_user_role_constraint', 'user_roles', type_='unique')
    # op.drop_constraint('_recipe_tag_constraint', 'recipe_tags', type_='unique')
    # op.drop_constraint('_recipe_ingredient_constraint', 'recipe_ingredients', type_='unique')
    # op.drop_constraint('_recipe_dish_type_constraint', 'recipe_dish_types', type_='unique')
    # op.drop_constraint('_recipe_cuisine_constraint', 'recipe_cuisines', type_='unique')
    op.add_column(
        "meals", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "meals", type_="foreignkey")
    op.create_foreign_key("meals_user_id_fkey", "meals", "users", ["user_id"], ["id"])
    op.drop_column("meals", "household_id")
    # ### end Alembic commands ###
